# Setup
title:               "AST 840: Stellar Astrophysics"
tagline:             'Stellar Astrophysics, Spring 2020'
description:         "Michigan State University - Astronomy 840: Stellar Astrophysics. A graduate-level course covering the essential physics governing the structure and evolution of stars."
url:               https://ast840.github.io
github:
  repository_name:   https://github.com/ast840

# About/contact
author:
  name:              Sean Couch
  url:               http://pa.msu.edu/~couch
  email:             scouch@msu.edu

theme: jekyll-theme-cayman
